version: 0.2

phases:
  build:
    commands:
      - echo building the jar
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/logistics-service.jar
  discard-paths: 'yes'
